### ISSUE TITLE
current version seems not be compatible with "improved sign in UI experience"

### ISSUE THREAD

**Issue by FallingEagle** [sankalpmukim/aws-accounts-manager#17] opened 2024-10-10 10:01 UTC
AWS is introducing new improved sign in UI experience which is not working with the "AWS accounts manager" plugin (tested under FF clone Waterfox). "Autofill" button does noting ie no fill in data fields, no move to the next page to fill MFA etc. It does only update when it was last used within the plugin itself.

When switch back to the "Legacy sign in" plugin works as expected: Autofill button puts data in the correct fields and move forward to the next screen with MFA.

**Comment by sankalpmukim** [comment] 2024-10-10 10:20
Hey @FallingEagle 
Thanks for raising this issue. It's a known problem and mentioned in #13.
I've been procrastinating on this for some time, will target finishing this off by the end of this week.

Duplicate of #13

**Closed by sankalpmukim** 2024-10-10 10:20 UTC

**Comment by sankalpmukim** [comment] 2024-10-10 10:21
Duplicate of #13
